# Mandatory settings

name: Jef Vlamings
paginate: 5
paginate_path: "/blog/page/:num/"
url: jefvlamings.be
blog_theme: light # Or use dark

# Optional settings

discus_identifier: jef-vlamings
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  dribbble: jefvlamings
  github: jefvlamings
  linkedin: jefvlamings
  twitter: jefvlamings
  email: vlamingsjef@gmail.com
  bitcoin: 1Nb661iZGgFiRC81fMhSKoRfuUYbZPextZ

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/stylesheets
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: blog/:slug
