# Site settings
title: Jef Vlamings
email: vlamingsjef@gmail.com
description: > #Description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.jefvlamings.com"
twitter_username: jefvlamings
github_username:  jefvlamings

# Build settings
markdown: kramdown
