# Site settings
title: Jef Vlamings - blog
email: vlamingsjef@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.jefvlamings.com"
twitter_username: jefvlamings
github_username:  jefvlamings

# Build settings
markdown: kramdown
