source 'https://rubygems.org'
ruby '2.3.1'

gem 'autoprefixer-rails'
gem 'html-proofer'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'mini_magick'
gem 'sass'
gem 'uglifier'
gem 'github-pages'